--- 
- name: Configure Multiple Cisco IOS Routing
  hosts: cisco_routers
  gather_facts: no
  connection: network_cli
  vars_files:
    - /home/champ/ansible/CSR8_OSPF.yml
  tasks:
    - name: Configure router process
      ios_config:
        src: /home/champ/ansible/OSPF_config_router_process.j2
#        parents: []
        save_when: modified
  
