---
- name: Configure Multiple Cisco IOS Interfaces
  hosts: cisco_routers
  gather_facts: no
  connection: network_cli
  vars_files:
    - /home/champ/CSR8.yml         # Router-specific variables
  tasks:
    - name: Configure multiple interfaces with different IPs
      cisco.ios.ios_interfaces:
        name: "{{ item.name }}"
        enabled: true
        description: "{{ item.description }}"
        ip_address: "{{ item.ip_address }}"
        netmask: "{{ item.netmask }}"
        state: up
      loop: "{{ interfaces }}"
      become: yes

