router_config:

  CSR8:

    interfaces:

      - name: GigabitEthernet2

        ip: 192.168.50.1

        mask: 255.255.255.0

      - name: GigabitEthernet3

        ip: 192.168.20.1

        mask: 255.255.255.0

  CSR9:

    interfaces:

      - name: GigabitEthernet2

        ip: 192.168.50.2

        mask: 255.255.255.0

      - name: GigabitEthernet3

        ip: 192.168.60.2

        mask: 255.255.255.0
