- name: Configure Cisco Routers

  hosts: all

  gather_facts: no
  
  become: yes

  vars_files:
    
    - /home/champ/router_config.yml
  tasks:

    - name: Configure interfaces

      ios_config:

        lines:

          - "interface {{ item.name }}"

          - "ip address {{ item.ip }} {{ item.mask }}"

          - "no shutdown"

        parents: []

      with_items: "{{ router_config[inventory_hostname]['interfaces'] }}"

      when: inventory_hostname in router_config
