--- 
- name: Configure Multiple Cisco IOS Interfaces 
  hosts: cisco_routers 
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Run multiple commands and evaluate the output
      cisco.ios.ios_command:
        commands:
          - show interfaces
      register: show_interfaces_output


    - name: Show output
      debug:
           var: show_interfaces_output.stdout
          
